Full initialization and configuration of the docker swarm cluster with glusterfs (#2)
* Environment is named platform for platform

* no dynamic secrets

* Typo in TERRAFORM_API_TOKEN name

* Typo in the name of the workspace.tfvars

* The given value is not suitable for var.server_roles declared at
│ variables.tf:42,1-24: element "infra": attribute "disks_gb": list of number
│ required.

* Debugging server initialization

* No dynamic initialization secrets

* Cant check a path before creation

* Add debugging informatoin

* fidning the workspace file

* Copy everything from deploy dir

* Debugging the configuration job

* No full update before installing gluster

* Firewall reset and bugfixing

* Bug on location for utilities.sh

* App path in workspace

* Rename APP_PATH_TEMP to VAR_PATH_TEMP

* APP replaced by VAR

* Workspace in temp path src

* Added debug information

* Added more debugging information

* More logging

* Filename debugging

* Bug in function that exports tffile

* Debugging server variables

* Label matche servername with -

* Apply terraform apply

* Debugging the entire remote configuration

* Bug with manager label validation against hostname

* Extra debugging information on gluster cluster

* firewall rules for glusterfs

* move volume_map and bricks_map outside the per-server loop, so they collect all bricks globally.

* Extra debugging and validation of gluster volumes

* The command substitution is missing (using backticks ` or $()) for get_terraform_data

* Extra logging

* More and more logging

* Updated loops

* This function uses 'force' when creating GlusterFS volumes.

diff --git a/.github/workflows/_pipeline.yml b/.github/workflows/_pipeline.yml
--- a/.github/workflows/_pipeline.yml
+++ b/.github/workflows/_pipeline.yml
@@ -18,14 +18,14 @@
 #  - Update or add matching "mounts" entries for relevant path types
 #
 # To add environment variables:
-#  - Use the APP_ prefix for application config (e.g., APP_PORT, APP_ENV)
+#  - Use the VAR_ prefix for application config (e.g., VAR_PORT, VAR_ENV)
 #  - Add them under the "env:" block of the relevant pipeline step
 #  - The SECRET_ prefix is dropped when exporting variables to the remote server.
 #
 # To add secrets:
 #  - Use the SECRET_ prefix (e.g., SECRET_API_KEY)
 #  - Add them under the "env:" block, referencing the secret store as needed
-#  - The APP_ prefix is dropped when exporting variables to the remote server.
+#  - The VAR_ prefix is dropped when exporting variables to the remote server.
 
 # Build and Deploy Jobs
 name: _InfraBuildDeploy
@@ -48,7 +48,7 @@ on:
 
 env:
   # Environment variables for the pipeline
-  APP_PATH_TEMP: /tmp/app
+  VAR_PATH_TEMP: /tmp/app
 
 jobs:
   # Terraform Plan and Apply
@@ -64,15 +64,6 @@ jobs:
       - name: Check Out
         uses: actions/checkout@v4
       
-      # Load secret uuid for Bitwarden
-      - name: Load Workspace Secrets
-        working-directory: ./deploy
-        run: |
-          echo "[*] Load secret identifiers ..."
-          source ./scripts/utilities.sh
-          load_secret_identifiers "./workspaces/${{ inputs.workspace }}.ws.json" "${{ inputs.environment }}"
-          echo "[*] Load secret identifiers ...DONE"
-
       # Set up GitHub Secrets
       - name: Get General Secrets
         uses: bitwarden/sm-action@v2
@@ -80,12 +71,12 @@ jobs:
         with:
           access_token: ${{ secrets.BITWARDEN_TOKEN }}
           secrets: |
-            $UUID_TERRAFORM_API_TOKEN > TERRAFORM_API_TOKEN
-            $UUID_KAMATERA_API_KEY > KAMATERA_API_KEY
-            $UUID_KAMATERA_API_SECRET > KAMATERA_API_SECRET
-            $UUID_KAMATERA_PUBLIC_KEY > KAMATERA_PUBLIC_KEY
-            $UUID_KAMATERA_PRIVATE_KEY > KAMATERA_PRIVATE_KEY
-            $UUID_KAMATERA_ROOT_PASSWORD > KAMATERA_ROOT_PASSWORD
+            d47e736b-2db8-47d5-b46b-b2c8016ece73 > TERRAFORM_API_TOKEN
+            357068b9-9f5f-4f79-940c-b2c8016cb88f > KAMATERA_API_KEY
+            6c9295a8-9fa4-4d38-8929-b2c8016d9b43 > KAMATERA_API_SECRET
+            6cc5b975-56a9-4d7a-80c7-b2c90151cce0 > KAMATERA_PUBLIC_KEY
+            f16fffe2-77b7-4d20-bf6c-b2c9015c71d3 > KAMATERA_PRIVATE_KEY
+            5083ae32-429d-428b-b7df-b2c901441bbb > KAMATERA_ROOT_PASSWORD
       
       # Set up the Terraform CLI
       - name: Set up Terraform
@@ -110,7 +101,7 @@ jobs:
           export TF_LOG=DEBUG
           export WORKSPACE=${{ inputs.workspace }}
           export ENVIRONMENT=${{ inputs.environment }}
-          export APP_PATH_TEMP=${{ env.APP_PATH_TEMP }}
+          export VAR_PATH_TEMP=${{ env.VAR_PATH_TEMP }}
           echo "[*] Server deployment and configuration ... APPLY"
           chmod +x ../scripts/terraform-apply.sh
           ../scripts/terraform-apply.sh
@@ -121,7 +112,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: terraform-output-${{ inputs.workspace }}
-          path: ${{ env.APP_PATH_TEMP }}/tf_output.json
+          path: ${{ env.VAR_PATH_TEMP }}/tf_output.json
           if-no-files-found: error
       
       # Check if Terraform cache exists
@@ -129,7 +120,7 @@ jobs:
         id: check-cache
         uses: actions/cache/restore@v4
         with:
-          path: ${{ env.APP_PATH_TEMP }}/tf_output.json
+          path: ${{ env.VAR_PATH_TEMP }}/tf_output.json
           key: terraform-output-${{ inputs.workspace }}
 
       # Upload the Terraform output as a job output
@@ -137,55 +128,55 @@ jobs:
         if: steps.check-cache.outputs.cache-hit != 'true'
         uses: actions/cache/save@v4
         with:
-          path: ${{ env.APP_PATH_TEMP }}/tf_output.json
+          path: ${{ env.VAR_PATH_TEMP }}/tf_output.json
           key: terraform-output-${{ inputs.workspace }}
 
   # Download the Terraform output artifact and parse it to find Swarm servers
   # This job will run if the cache is not hit or if the initialize input is set to true
   # Parses the output to find Swarm servers and sets them as a matrix for the next jobs
-  # restore:
-  #   name: Download Terraform Output
-  #   runs-on: ubuntu-latest
-  #   needs: [terraform]
-  #   environment: ${{ inputs.environment }}
-  #   if: always()
-  #   outputs:
-  #     matrix: ${{ steps.parse.outputs.matrix }}
-  #   steps:
-  #     # Download Terraform Artifact
-  #     - name: Download Terraform Artifact
-  #       if: inputs.infrastructure == true
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: terraform-output-${{ inputs.workspace }}
-  #         path: ${{ env.APP_PATH_TEMP }}
+  restore:
+    name: Download Terraform Output
+    runs-on: ubuntu-latest
+    needs: [terraform]
+    environment: ${{ inputs.environment }}
+    if: always()
+    outputs:
+      matrix: ${{ steps.parse.outputs.matrix }}
+    steps:
+      # Download Terraform Artifact
+      - name: Download Terraform Artifact
+        if: inputs.infrastructure == true
+        uses: actions/download-artifact@v4
+        with:
+          name: terraform-output-${{ inputs.workspace }}
+          path: ${{ env.VAR_PATH_TEMP }}
 
-  #     # Restore Terraform Cache
-  #     - name: Restore Terraform Cache
-  #       id: restore-cache
-  #       if: inputs.infrastructure != true
-  #       uses: actions/cache/restore@v4
-  #       with:
-  #         path: ${{ env.APP_PATH_TEMP }}/tf_output.json
-  #         key: terraform-output-${{ inputs.workspace }}
+      # Restore Terraform Cache
+      - name: Restore Terraform Cache
+        id: restore-cache
+        if: inputs.infrastructure != true
+        uses: actions/cache/restore@v4
+        with:
+          path: ${{ env.VAR_PATH_TEMP }}/tf_output.json
+          key: terraform-output-${{ inputs.workspace }}
 
-  #     # Check if the artifact exists
-  #     - name: Validate Terraform Output
-  #       run: |
-  #         if [ ! -f ${{ env.APP_PATH_TEMP }}/tf_output.json ]; then
-  #           echo "[!] Artifact terraform-output-${{ inputs.workspace }} not found or tf_output.json missing. Exiting."
-  #           exit 1
-  #         fi
+      # Check if the artifact exists
+      - name: Validate Terraform Output
+        run: |
+          if [ ! -f ${{ env.VAR_PATH_TEMP }}/tf_output.json ]; then
+            echo "[!] Artifact terraform-output-${{ inputs.workspace }} not found or tf_output.json missing. Exiting."
+            exit 1
+          fi
 
-  #     # Parse Terraform Output to find Swarm Servers
-  #     - name: Parse Swarm Servers
-  #       id: parse
-  #       run: |
-  #         matrix=$(jq -c '.' ${{ env.APP_PATH_TEMP }}/tf_output.json)
-  #         echo "================"
-  #         echo "$matrix"
-  #         echo "================"
-  #         echo "matrix=$matrix" >> $GITHUB_OUTPUT
+      # Parse Terraform Output to find Swarm Servers
+      - name: Parse Swarm Servers
+        id: parse
+        run: |
+          matrix=$(jq -c '.' ${{ env.VAR_PATH_TEMP }}/tf_output.json)
+          echo "================"
+          echo "$matrix"
+          echo "================"
+          echo "matrix=$matrix" >> $GITHUB_OUTPUT
 
   # Initialize the Swarm Cluster
   # This job will run if the cache is not hit or if the initialize input is set to true
@@ -195,124 +186,107 @@ jobs:
   # - installing docker and initializing the Swarm cluster
   # - mounting the necessary disks
   # - installing glusterfs
-  # initialization:
-  #   name: Initialize Cluster
-  #   needs: [restore]
-  #   runs-on: ubuntu-latest
-  #   environment: ${{ inputs.environment }}
-  #   if: ${{ inputs.infrastructure == true }}
-  #   strategy:
-  #     matrix: ${{ fromJson(needs.restore.outputs.matrix) }}
-  #   steps:
-  #     # Check out the repo
-  #     - name: Check Out
-  #       uses: actions/checkout@v4
+  initialization:
+    name: Initialize Cluster
+    needs: [restore]
+    runs-on: ubuntu-latest
+    environment: ${{ inputs.environment }}
+    if: ${{ inputs.infrastructure == true }}
+    strategy:
+      matrix: ${{ fromJson(needs.restore.outputs.matrix) }}
+    steps:
+      # Check out the repo
+      - name: Check Out
+        uses: actions/checkout@v4
 
-  #     # Load secret uuid for Bitwarden
-  #     - name: Load Workspace Secrets
-  #       working-directory: ./deploy
-  #       run: |
-  #         echo "[*] Load secret identifiers ..."
-  #         source ./scripts/utilities.sh
-  #         load_secret_identifiers "./workspaces/${{ inputs.workspace }}.ws.json" "${{ inputs.environment }}"
-  #         echo "[*] Load secret identifiers ...DONE"
+      # Set up GitHub Secrets
+      - name: Get General Secrets
+        uses: bitwarden/sm-action@v2
+        id: get-secrets
+        with:
+          access_token: ${{ secrets.BITWARDEN_TOKEN }}
+          secrets: |
+            f16fffe2-77b7-4d20-bf6c-b2c9015c71d3 > KAMATERA_PRIVATE_KEY
 
-  #     # Set up GitHub Secrets
-  #     - name: Get General Secrets
-  #       uses: bitwarden/sm-action@v2
-  #       id: get-secrets
-  #       with:
-  #         access_token: ${{ secrets.BITWARDEN_TOKEN }}
-  #         secrets: |
-  #           $UUID_KAMATERA_PRIVATE_KEY > KAMATERA_PRIVATE_KEY
+      # Set up SSH connection
+      - name: Set up SSH connection
+        env:
+          KAMATERA_PRIVATE_KEY: ${{ steps.get-secrets.outputs.KAMATERA_PRIVATE_KEY }}
+        run: |
+          mkdir -p ~/.ssh
+          echo "$KAMATERA_PRIVATE_KEY" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
 
-  #     # Set up SSH connection
-  #     - name: Set up SSH connection
-  #       env:
-  #         KAMATERA_PRIVATE_KEY: ${{ steps.get-secrets.outputs.KAMATERA_PRIVATE_KEY }}
-  #       run: |
-  #         mkdir -p ~/.ssh
-  #         echo "$KAMATERA_PRIVATE_KEY" > ~/.ssh/id_rsa
-  #         chmod 600 ~/.ssh/id_rsa
+      # Step: Copy the key securely to the remote server using scp
+      - name: Upload Private Key
+        run: |
+          scp -o StrictHostKeyChecking=no ~/.ssh/id_rsa root@${{ matrix.ip }}:/root/.ssh/id_rsa_temp || { echo "[x] Failed to transfer private key to remote server"; exit 1; }
 
-  #     # Step: Copy the key securely to the remote server using scp
-  #     - name: Upload Private Key
-  #       run: |
-  #         scp -o StrictHostKeyChecking=no ~/.ssh/id_rsa root@${{ matrix.ip }}:/root/.ssh/id_rsa_temp || { echo "[x] Failed to transfer private key to remote server"; exit 1; }
-
-  #     # Step: Initialize the Swarm cluster
-  #     - name: Initialize Swarm Cluster
-  #       env:
-  #         APP_WORKSPACE: ${{ inputs.workspace }}
-  #       run: |
-  #         echo "[*] Initializing swarm cluster on ${{ matrix.ip }} ..."
-  #         chmod +x deploy/scripts/initialize-swarm-server.sh
-  #         ./deploy/scripts/initialize-swarm-server.sh "${{ matrix.ip }}" "${{ matrix.private_ip }}" "${{ matrix.manager_ip }}"
-  #         echo "[*] Initializing swarm cluster on ${{ matrix.ip }} ...DONE"
+      # Step: Initialize the Swarm cluster
+      - name: Initialize Swarm Cluster
+        env:
+          VAR_WORKSPACE: ${{ inputs.workspace }}
+        run: |
+          echo "[*] Initializing swarm cluster on ${{ matrix.ip }} ..."
+          chmod +x deploy/scripts/initialize-swarm-server.sh
+          ./deploy/scripts/initialize-swarm-server.sh "${{ matrix.ip }}" "${{ matrix.private_ip }}" "${{ matrix.manager_ip }}"
+          echo "[*] Initializing swarm cluster on ${{ matrix.ip }} ...DONE"
 
   # Configure the Swarm Cluster
   # This job will run if the restore and initialization jobs are successful or skipped
   # Configures the Swarm cluster with the necessary settings and secrets
-  # configuration:
-  #   name: Configure Cluster
-  #   needs: [restore, initialization]
-  #   runs-on: ubuntu-latest
-  #   environment: ${{ inputs.environment }}
-  #   if: ${{ always() && !contains(needs.*.result, 'failure') }}
-  #   strategy:
-  #     matrix: ${{ fromJson(needs.restore.outputs.matrix) }}
-  #   steps:
-  #     # Check out the repo
-  #     - name: Check Out
-  #       uses: actions/checkout@v4
+  configuration:
+    name: Configure Cluster
+    needs: [restore, initialization]
+    runs-on: ubuntu-latest
+    environment: ${{ inputs.environment }}
+    if: ${{ always() && !contains(needs.*.result, 'failure') }}
+    strategy:
+      matrix: ${{ fromJson(needs.restore.outputs.matrix) }}
+    steps:
+      # Check out the repo
+      - name: Check Out
+        uses: actions/checkout@v4
 
-  #     # Load secret uuid for Bitwarden
-  #     - name: Load Workspace Secrets
-  #       working-directory: ./deploy
-  #       run: |
-  #         echo "[*] Load secret identifiers ..."
-  #         source ./scripts/utilities.sh
-  #         load_secret_identifiers "./workspaces/${{ inputs.workspace }}.ws.json" "${{ inputs.environment }}"
-  #         echo "[*] Load secret identifiers ...DONE"
+      # Set up GitHub Secrets
+      - name: Get General Secrets
+        uses: bitwarden/sm-action@v2
+        id: get-secrets
+        with:
+          access_token: ${{ secrets.BITWARDEN_TOKEN }}
+          secrets: |
+            d47e736b-2db8-47d5-b46b-b2c8016ece73 > TERRAFORM_API_TOKEN
+            357068b9-9f5f-4f79-940c-b2c8016cb88f > KAMATERA_API_KEY
+            6c9295a8-9fa4-4d38-8929-b2c8016d9b43 > KAMATERA_API_SECRET
+            6cc5b975-56a9-4d7a-80c7-b2c90151cce0 > KAMATERA_PUBLIC_KEY
+            f16fffe2-77b7-4d20-bf6c-b2c9015c71d3 > KAMATERA_PRIVATE_KEY
+            5083ae32-429d-428b-b7df-b2c901441bbb > KAMATERA_ROOT_PASSWORD
+            09171644-23c8-4b7f-9015-b2e5015a4572 > PLATFORM_USERNAME
+            ffa5e6f9-de6a-47fa-887e-b2e5015ae1a4 > PLATFORM_PASSWORD
+            f53a76ab-b87f-4af0-9aa4-b2d1016aba2b > VERSIO_USERNAME
+            3d7bbfcd-18a5-4762-9064-b2d1016aef63 > VERSIO_PASSWORD
 
-  #     # Set up GitHub Secrets
-  #     - name: Get General Secrets
-  #       uses: bitwarden/sm-action@v2
-  #       id: get-secrets
-  #       with:
-  #         access_token: ${{ secrets.BITWARDEN_TOKEN }}
-  #         secrets: |
-  #           $UUID_KAMATERA_API_KEY > KAMATERA_API_KEY
-  #           $UUID_KAMATERA_API_SECRET > KAMATERA_API_SECRET
-  #           $UUID_KAMATERA_PUBLIC_KEY > KAMATERA_PUBLIC_KEY
-  #           $UUID_KAMATERA_PRIVATE_KEY > KAMATERA_PRIVATE_KEY
-  #           $UUID_KAMATERA_ROOT_PASSWORD > KAMATERA_ROOT_PASSWORD
-  #           $UUID_PLATFORM_USERNAME > PLATFORM_USERNAME
-  #           $UUID_PLATFORM_PASSWORD > PLATFORM_PASSWORD
-  #           $UUID_VERSIO_USERNAME > VERSIO_USERNAME
-  #           $UUID_VERSIO_PASSWORD > VERSIO_PASSWORD
+      # Set up SSH connection
+      - name: Set up SSH connection
+        env:
+          KAMATERA_PRIVATE_KEY: ${{ steps.get-secrets.outputs.KAMATERA_PRIVATE_KEY }}
+        run: |
+          mkdir -p ~/.ssh
+          echo "$KAMATERA_PRIVATE_KEY" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
 
-  #     # Set up SSH connection
-  #     - name: Set up SSH connection
-  #       env:
-  #         KAMATERA_PRIVATE_KEY: ${{ steps.get-secrets.outputs.KAMATERA_PRIVATE_KEY }}
-  #       run: |
-  #         mkdir -p ~/.ssh
-  #         echo "$KAMATERA_PRIVATE_KEY" > ~/.ssh/id_rsa
-  #         chmod 600 ~/.ssh/id_rsa
-
-  #     # Step: Configure Server
-  #     - name: Configure Server
-  #       env:
-  #         VAR_MATRIX: ${{ needs.restore.outputs.matrix }}
-  #         VAR_ENVIRONMENT: ${{ inputs.environment }}
-  #         VAR_WORKSPACE: ${{ inputs.workspace }}
-  #         SECRET_PLATFORM_USERNAME: ${{ steps.get-secrets.outputs.PLATFORM_USERNAME }}
-  #         SECRET_PLATFORM_PASSWORD: ${{ steps.get-secrets.outputs.PLATFORM_PASSWORD }}
-  #         SECRET_VERSIO_USERNAME : ${{ steps.get-secrets.outputs.VERSIO_USERNAME }}
-  #         SECRET_VERSIO_PASSWORD : ${{ steps.get-secrets.outputs.VERSIO_PASSWORD }}
-  #       run: |
-  #         echo "[*] Configuring swarm server ${{ matrix.ip }} ..."
-  #         chmod +x deploy/scripts/configure-swarm-server.sh
-  #         ./deploy/scripts/configure-swarm-server.sh "${{ matrix.ip }}" "$VAR_MATRIX"
-  #         echo "[*] Configuring swarm server ${{ matrix.ip }} ...DONE"
+      # Step: Configure Server
+      - name: Configure Server
+        env:
+          VAR_MATRIX: ${{ needs.restore.outputs.matrix }}
+          VAR_ENVIRONMENT: ${{ inputs.environment }}
+          VAR_WORKSPACE: ${{ inputs.workspace }}
+          SECRET_PLATFORM_USERNAME: ${{ steps.get-secrets.outputs.PLATFORM_USERNAME }}
+          SECRET_PLATFORM_PASSWORD: ${{ steps.get-secrets.outputs.PLATFORM_PASSWORD }}
+          SECRET_VERSIO_USERNAME : ${{ steps.get-secrets.outputs.VERSIO_USERNAME }}
+          SECRET_VERSIO_PASSWORD : ${{ steps.get-secrets.outputs.VERSIO_PASSWORD }}
+        run: |
+          echo "[*] Configuring swarm server ${{ matrix.ip }} ..."
+          chmod +x deploy/scripts/configure-swarm-server.sh
+          ./deploy/scripts/configure-swarm-server.sh "${{ matrix.ip }}" "$VAR_MATRIX"
+          echo "[*] Configuring swarm server ${{ matrix.ip }} ...DONE"
